# -*- coding: utf-8 -*-
"""plot_reaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxMxolCASnP5mIk1CmM501QaHFy2Qyl0
"""

import matplotlib.pyplot as plt
import numpy as np

# Coordenadas da reação
reaction_coordinate = np.linspace(0, 10, 500)

# Definindo diferentes parâmetros para quatro reações
parameters = [
    {'delta_G_reactants': 0, 'delta_G_products': -12.6317763, 'delta_G_activation': 8.34400047, 'label': 'Conformação B1'},
    {'delta_G_reactants': 0, 'delta_G_products': -5.78815224, 'delta_G_activation': 11.12261475, 'label': 'Conformação B2'},
    {'delta_G_reactants': 0, 'delta_G_products': -12.59851827, 'delta_G_activation': 10.38780054, 'label': 'Conformação D1'},
    {'delta_G_reactants': 0, 'delta_G_products': -1.33157622, 'delta_G_activation': 11.22427137, 'label': 'Conformação D2'},
]

# Criando o gráfico
plt.figure(figsize=(12, 8))

# Plotando cada reação com melhorias na visualização
colors = ['blue', 'orange', 'green', 'red']  # Cores distintas para cada reação
linestyles = ['-', '--', '-.', ':']  # Estilos de linha diferentes

for i, params in enumerate(parameters):
    delta_G_reactants = params['delta_G_reactants']
    delta_G_products = params['delta_G_products']
    delta_G_activation = params['delta_G_activation']

    # Definindo a energia de Gibbs ao longo da coordenada da reação
    Gibbs_energy = np.zeros_like(reaction_coordinate)
    # Parte antes da barreira de ativação
    Gibbs_energy[:250] = delta_G_reactants + (delta_G_activation - delta_G_reactants) * np.exp(-0.5 * (reaction_coordinate[:250] - 5)**2)
    # Parte após a barreira de ativação
    Gibbs_energy[250:] = delta_G_products + (delta_G_activation - delta_G_products) * np.exp(-0.5 * (reaction_coordinate[250:] - 5)**2)

    # Plotagem com melhorias
    plt.plot(reaction_coordinate, Gibbs_energy, color=colors[i], linestyle=linestyles[i % len(linestyles)], linewidth=2.0, label=params['label'])

    # Adicionando marcadores nos pontos de reagentes, estado de transição e produtos
    plt.scatter([0], [delta_G_reactants], color=colors[i], marker='o', s=100)  # Ponto de reagentes
    plt.scatter([5], [delta_G_activation], color=colors[i], marker='s', s=100)  # Ponto de estado de transição
    plt.scatter([10], [delta_G_products], color=colors[i], marker='^', s=100)  # Ponto de produtos

# Etiquetas e título
plt.xlabel('Coordenada de Reação')
plt.ylabel('Energia Livre de Gibbs (kcal/mol)')
plt.title('Diagrama de Energia de Ativação - R.nitrato/aug-cc-pVDZ')

# Ajustando a legenda para mostrar apenas uma vez
plt.legend()

# Mostrando o gráfico
plt.grid(True)
plt.show()